### ISSUE TITLE
broken as of solid-start 0.3.x

### ISSUE THREAD

**Issue by jay3332** [high1/solid-jsx#36]
solid-jsx produces the following error when trying to render mdx:

TypeError: Comp is not a function
    at Proxy.createComponent (file:///Users/jay3332/Projects/coined-website/node_modules/solid-js/dist/server.js:328:15)
    at _createMdxContent (/Users/jay3332/Projects/coined-website/src/routes/terms.mdx:24:35)
    at Proxy.createComponent (file:///Users/jay3332/Projects/coined-website/node_modules/solid-js/dist/server.js:328:15)
    at get children [as children] (/Users/jay3332/Projects/coined-website/src/routes/terms.mdx:56:36)
    at Object.get [as children] (file:///Users/jay3332/Projects/coined-website/node_modules/solid-js/dist/server.js:349:26)
    at Proxy.ssrElement (file:///Users/jay3332/Projects/coined-website/node_modules/solid-js/web/dist/server.js:303:112)
    at get children [as children] (/Users/jay3332/Projects/coined-website/src/layouts/Article.tsx:42:36)
    at get children [as children] (/Users/jay3332/Projects/coined-website/node_modules/solid-jsx/dist/jsx-runtime.js:6:680)
    at file:///Users/jay3332/Projects/coined-website/node_modules/solid-js/dist/server.js:206:35
    at file:///Users/jay3332/Projects/coined-website/node_modules/solid-js/dist/server.js:169:49
    at createMemo (file:///Users/jay3332/Projects/coined-website/node_modules/solid-js/dist/server.js:88:9)
    at children (file:///Users/jay3332/Projects/coined-website/node_modules/solid-js/dist/server.js:169:16)
    at file:///Users/jay3332/Projects/coined-website/node_modules/solid-js/dist/server.js:206:14
    at createMemo (file:///Users/jay3332/Projects/coined-website/node_modules/solid-js/dist/server.js:88:9)
    at provider (file:///Users/jay3332/Projects/coined-website/node_modules/solid-js/dist/server.js:201:12)
    at Proxy.createComponent (file:///Users/jay3332/Projects/coined-website/node_modules/solid-js/dist/server.js:328:15)
    at F (/Users/jay3332/Projects/coined-website/node_modules/solid-jsx/dist/jsx-runtime.js:6:586)

downgrading to solid-start 0.2 fixed the issue.

**Comment by kixelated** [comment]
I'm getting the same error, but without solid-start. I'm using solidjs/router which might be the root cause.

>Uncaught Error: TypeError: Comp is not a function
TypeError: Comp is not a function at https://localhost:4444/index.fdd53e66.js:3029:24 at untrack (https://localhost:4444/index.fdd53e66.js:2236:35) at createComponent (https://localhost:4444/index.fdd53e66.js:3029:12) at MDXContent (https://localhost:4444/index.fdd53e66.js:14852:37) at https://localhost:4444/index.fdd53e66.js:3029:24 at untrack (https://localhost:4444/index.fdd53e66.js:2240:16) at createComponent (https://localhost:4444/index.fdd53e66.js:3029:12) at shared.element.component.element.element [as outlet] (https://localhost:4444/index.fdd53e66.js:3885:63) at get children [as children] (https://localhost:4444/index.fdd53e66.js:4254:34) at Object.fn (https://localhost:4444/index.fdd53e66.js:2800:43)
